### ISSUE TITLE
Character missing? 

### ISSUE THREAD

**Issue by JerimSD** [gloeyisk/Ubuntu-Font#1]
![screenshot_20181116-224827](https://user-images.githubusercontent.com/14279682/48649266-61fb0b80-e9f2-11e8-80a1-8ac34e0dd6b8.png)
On lock screen, : between the hours and the minutes is missing or maybe there is a problem with the encoding
(on Pixel 2XL)

**Comment by gloeyisk** [comment]
> ![screenshot_20181116-224827](https://user-images.githubusercontent.com/14279682/48649266-61fb0b80-e9f2-11e8-80a1-8ac34e0dd6b8.png)
> On lock screen, : between the hours and the minutes is missing or maybe there is a problem with the encoding
> (on Pixel 2XL)

Currently for Pixel-based ROMs the glyph is missing (semicolon on lockscreen).
I'll fixed it *ASAP*. Thanks for the report!

**Comment by gloeyisk** [comment]
@JerimSD I've build a new one, can you confirm that the lockscreen issue is fixed? Thanks.
