### ISSUE TITLE
"-1" Superscript missing

### ISSUE THREAD

**Issue by kurtzberger** [gloeyisk/Ubuntu-Font#2]
Similar to #1. 
"-1" Superscript is not showing up/displaying correctly. 
See [this screenshot](https://photos.app.goo.gl/qrHFgBRj1u2HeqYt7)

Thanks so much!

**Comment by gloeyisk** [comment]
> Similar to #1.
> "-1" Superscript is not showing up/displaying correctly.
> See [this screenshot](https://photos.app.goo.gl/qrHFgBRj1u2HeqYt7)
> 
> Thanks so much!

Which ROM you're running on? It seems Pixel based ROM?

**Comment by kurtzberger** [comment]
Yes that's right. Stock Android 9 on a Pixel 3 XL.

**Comment by gloeyisk** [comment]
@kurtzberger I've build a new one, can you confirm the current issue is fixed?

**Comment by kurtzberger** [comment]
@gloeyisk thanks for the new build! Unfortunately, it's still displaying the same way.

**Comment by gloeyisk** [comment]
> 
> 
> @gloeyisk thanks for the new build! Unfortunately, it's still displaying the same way.

I need to ask something, is that your default font Google Sans instead of Roboto?

**Comment by kurtzberger** [comment]
Yes that's right. The default font on Pixel 3 running Android P is Google's Product Sans.

**Comment by gloeyisk** [comment]
[Roboto.zip](https://github.com/gloeyisk/Ubuntu-Font/files/2829015/Roboto.zip)


> 
> 
> Yes that's right. The default font on Pixel 3 running Android P is Google's Product Sans.

Can you remove the Ubuntu font first, reboot it once, and flash this flashable Roboto font zip?
After that reboot it to system and make sure the font changed to Roboto (default font), and try to re-flash Ubuntu once again.

**Comment by kurtzberger** [comment]
> [Roboto.zip](https://github.com/gloeyisk/Ubuntu-Font/files/2829015/Roboto.zip)
> 
> > Yes that's right. The default font on Pixel 3 running Android P is Google's Product Sans.
> 
> Can you remove the Ubuntu font first, reboot it once, and flash this flashable Roboto font zip?
> After that reboot it to system and make sure the font changed to Roboto (default font), and try to re-flash Ubuntu once again.

Hmm that isn't working. It appears that even with Roboto installed some Google apps still use product sans within the app? See [this screenshot](https://photos.app.goo.gl/sprf759FE92RG3n16) after I flashed the Roboto zip.

**Comment by gloeyisk** [comment]
> > [Roboto.zip](https://github.com/gloeyisk/Ubuntu-Font/files/2829015/Roboto.zip)
> > > Yes that's right. The default font on Pixel 3 running Android P is Google's Product Sans.
> > 
> > 
> > Can you remove the Ubuntu font first, reboot it once, and flash this flashable Roboto font zip?
> > After that reboot it to system and make sure the font changed to Roboto (default font), and try to re-flash Ubuntu once again.
> 
> Hmm that isn't working. It appears that even with Roboto installed some Google apps still use product sans within the app? See [this screenshot](https://photos.app.goo.gl/sprf759FE92RG3n16) after I flashed the Roboto zip.

How about to use another calculator app?

**Comment by kurtzberger** [comment]
I suppose I can do that. I can confirm that some of Google's apps are using different fonts in some places.

Thanks for your help
