### ISSUE TITLE
TRY(Turkish Lira) Symbol

### ISSUE THREAD

**Issue by eimrhan** [gloeyisk/Ubuntu-Font#3]
Turkish Lira (TRY) Symbol is looking as ":"

**Comment by gloeyisk** [comment]
> 
> 
> Turkish Lira (TRY) Symbol is looking as ":"

Could you send me the screenshot for your issue?

**Comment by eimrhan** [comment]
> > Turkish Lira (TRY) Symbol is looking as ":"
> 
> Could you send me the screenshot for your issue?

https://i.hizliresim.com/7a3DBN.jpg

**Comment by gloeyisk** [comment]
> > > Turkish Lira (TRY) Symbol is looking as ":"
> > 
> > 
> > Could you send me the screenshot for your issue?
> 
> https://i.hizliresim.com/7a3DBN.jpg

Can't access the link, use another mirror.

**Comment by gloeyisk** [comment]
Closed by mistake.

**Comment by eimrhan** [comment]
> > > > Turkish Lira (TRY) Symbol is looking as ":"
> > > 
> > > 
> > > Could you send me the screenshot for your issue?
> > 
> > 
> > https://i.hizliresim.com/7a3DBN.jpg
> 
> Can't access the link, use another mirror.

Try this please.
https://ibb.co/2PT3nQG

**Comment by gloeyisk** [comment]
> > > > > Turkish Lira (TRY) Symbol is looking as ":"
> > > > 
> > > > 
> > > > Could you send me the screenshot for your issue?
> > > 
> > > 
> > > https://i.hizliresim.com/7a3DBN.jpg
> > 
> > 
> > Can't access the link, use another mirror.
> 
> Try this please.
> https://ibb.co/2PT3nQG

Sorry for quite late answer, did you install using this Ubuntu font? I'll have to re-check your issue tomorrow.
Hope it'll be fixed.

**Comment by gloeyisk** [comment]
> > > > > Turkish Lira (TRY) Symbol is looking as ":"
> > > > 
> > > > 
> > > > Could you send me the screenshot for your issue?
> > > 
> > > 
> > > https://i.hizliresim.com/7a3DBN.jpg
> > 
> > 
> > Can't access the link, use another mirror.
> 
> Try this please.
> https://ibb.co/2PT3nQG

Sorry for quite late answer, did you still using this Ubuntu font? I'll have to re-check your issue tomorrow.
Hope it'll be fixed.

**Comment by eimrhan** [comment]
> > > > > > Turkish Lira (TRY) Symbol is looking as ":"
> > > > > 
> > > > > 
> > > > > Could you send me the screenshot for your issue?
> > > > 
> > > > 
> > > > https://i.hizliresim.com/7a3DBN.jpg
> > > 
> > > 
> > > Can't access the link, use another mirror.
> > 
> > 
> > Try this please.
> > https://ibb.co/2PT3nQG
> 
> Sorry for quite late answer, did you still using this Ubuntu font? I'll have to re-check your issue tomorrow.
> Hope it'll be fixed.

I've removed it after see this "other fonts" issue.
https://ibb.co/8K047SQ
https://ibb.co/xFD8WB0

**Comment by gloeyisk** [comment]
> > > > > > > Turkish Lira (TRY) Symbol is looking as ":"
> > > > > > 
> > > > > > 
> > > > > > Could you send me the screenshot for your issue?
> > > > > 
> > > > > 
> > > > > https://i.hizliresim.com/7a3DBN.jpg
> > > > 
> > > > 
> > > > Can't access the link, use another mirror.
> > > 
> > > 
> > > Try this please.
> > > https://ibb.co/2PT3nQG
> > 
> > 
> > Sorry for quite late answer, did you still using this Ubuntu font? I'll have to re-check your issue tomorrow.
> > Hope it'll be fixed.
> 
> I've removed it after see this "other fonts" issue.
> https://ibb.co/8K047SQ
> https://ibb.co/xFD8WB0

I'm so sorry if I was made a mistake that you chosen to remove the module. For further information, did you've Telegram account?

**Comment by eimrhan** [comment]
> > > > > > > > Turkish Lira (TRY) Symbol is looking as ":"
> > > > > > > 
> > > > > > > 
> > > > > > > Could you send me the screenshot for your issue?
> > > > > > 
> > > > > > 
> > > > > > https://i.hizliresim.com/7a3DBN.jpg
> > > > > 
> > > > > 
> > > > > Can't access the link, use another mirror.
> > > > 
> > > > 
> > > > Try this please.
> > > > https://ibb.co/2PT3nQG
> > > 
> > > 
> > > Sorry for quite late answer, did you still using this Ubuntu font? I'll have to re-check your issue tomorrow.
> > > Hope it'll be fixed.
> > 
> > 
> > I've removed it after see this "other fonts" issue.
> > https://ibb.co/8K047SQ
> > https://ibb.co/xFD8WB0
> 
> I'm so sorry if I was made a mistake that you chosen to remove the module. For further information, did you've Telegram account?

It's no problem. https://t.me/eimrhan

**Comment by gloeyisk** [comment]
Hi! Now missing Super/Sub Scripts and Signs are fixed. Happy flashing.
